### ISSUE TITLE
Question: Could we use the same mechanism for Quantization?

### ISSUE THREAD

**Issue by LLukas22** [EricLBuehler/candle-lora#1]
Just an idea but couldn't the `LayerLike` mechanism be used to simply swap e.g. Linear-Layers in a model with quantized Linear-Layers?
This would make quantization of already implemented models trivial.

**Comment by EricLBuehler** [comment]
Yes, this is what I had in mind. With this mechanism, any layer can be swapped out. In fact, plan on adding a parameter to `LoraConfig` that automatically quantizes all tensors, so no new layers would need to be implemented.

**Comment by EricLBuehler** [comment]
Great! Thank you for your interest - I will look into implementing quantized lora types when quantized tensors become more fully featured.

**Comment by EricLBuehler** [comment]
I am closing this so that it does not become a stale issue, but feel free to reopen. I am looking forward to more general support for `QuantizedTensor`!
