### ISSUE TITLE
Is there any way to save lora-converted model?

### ISSUE THREAD

**Issue by Adamska1008** [EricLBuehler/candle-lora#12]
I tried to fine tune [TinyLlama](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) with this crate. I use `candle-lora/candle-lora-transformers/examples/llama.rs` to load `model.safetensors`, do stuff about training, eventually find that there's no way to save the model in safetensors format. 

I tried to implement a save method myself wrapping `candle_core::safetensors::save()`, but how can I get the weight of lora part? All I can get is the raw model before it converted to lora model. 

For example, if you run `/candle-lora-macro/examples/linear.rs`, by `println!("{:?}", model.a);` you will see it printed as Linear struct, not a LoraLinear struct, and you can't get `ff_a`、`ff_b` from `model.a`, despite that the model is converted to a lora model.

**Comment by EricLBuehler** [comment]
This is implemented/fixed in #13. Please note that the weight naming is incompatible with  peft at the moment. If this is a problem, please feel free to raise an issue and I will fix it

**Comment by Adamska1008** [comment]
> This is implemented/fixed in #13 which has been merged. Please note that the weight naming is incompatible with peft at the moment. If this is a problem, please feel free to raise an issue and I will fix it

Thank you very much! I tried this and get a 536KB `safetensors` file with header:
```
{"lora_llamaa0.weight":{"data_offsets":[0,512000],"dtype":"F16","shape":[8,32000]},"lora_llamab0.weight":{"data_offsets":[512000,544768],"dtype":"F16","shape":[2048,8]}}
``` 
Is it as expected? I also want to know how to apply the Lora tensors after loading a `VarBuilder` from original model.

**Comment by EricLBuehler** [comment]
No, the prefix was incorrect but it should be fixed now. To load the Lora tensors, pass `get_lora_model` the `VarBuilder` returned by `from_mmaped_safetensors`. Here is an example of loading the `VarBuilder`:
> https://github.com/EricLBuehler/candle-lora/blob/a7ea48a71e9defb7bd6bef0ffb54d0a0810cd595/candle-lora-transformers/examples/llama.rs#L202

That `vb` is then passed to `get_lora_model`:
> https://github.com/EricLBuehler/candle-lora/blob/a7ea48a71e9defb7bd6bef0ffb54d0a0810cd595/candle-lora-transformers/src/llama.rs#L573-L591

**Comment by EricLBuehler** [comment]
Glad to help!
