### ISSUE TITLE
Examples for Llama model architecture

### ISSUE THREAD

**Issue by okpatil4u** [EricLBuehler/candle-lora#2]
Hello Eric, this looks like great work ! Thank you !!

Can you please add examples for both training and inference for Llama model using candle-lora ? Is it supported through this work ?

**Comment by EricLBuehler** [comment]
Yes! With my [candle-lora-macro](https://github.com/EricLBuehler/candle-lora-macro) library, all you need to do is derive the `AutoLoraConvert` and add the `replace_layer_fields` to all model structs of a LLama model. They will replace the concrete types and automate the conversion process. Then, call the conversion method on each model struct.

I plan on adding an example shortly. If you have any questions, let me know!

**Comment by okpatil4u** [comment]
This is amazing. Is the training example possible as well ?

**Comment by EricLBuehler** [comment]
Yes, once you convert to a LoRA model you could fine-tune it. After finetuning, you can merge the weights to speed up inference.

**Comment by EricLBuehler** [comment]
I am closing this so that it does not become a stale issue, but feel free to reopen. I will be adding a LoRA example for Llama and soon!

**Comment by okpatil4u** [comment]
Sounds good, thank you !
